# Generated by Django 5.2 on 2025-04-19 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_filme_delete_livro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filme',
            name='publicado_em',
        ),
    ]
